version: "3.3"

services:

  api:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - nats
    networks:
      - internal

  products:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'mortgage_project'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'aa346134aa'
    ports:
      - '5432:5432'
  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
  link:
    build:
      context: .
    image: demo
    environment:
      SERVICES: link
    env_file: docker-compose.env
    depends_on:
      - db
    networks:
      - internal

  sms:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    depends_on:
      - db
    networks:
      - internal

  auth:
    build:
      context: .
    image: demo
    environment:
      SERVICES: auth
    env_file: docker-compose.env
    depends_on:
      - db
    networks:
      - internal

  docs:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    depends_on:
      - db
    networks:
      - internal


  file:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    depends_on:
      - db
    networks:
      - internal


  order:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    depends_on:
      - db
    networks:
      - internal

  ceil:
    build:
      context: .
    image: demo
    env_file: docker-compose.env
    depends_on:
      - db
    networks:
      - internal


networks:
  internal:

volumes:
  data:
